services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env  # Reference to your .env file
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Use the environment variable from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Use the environment variable from .env
      POSTGRES_DB: ${POSTGRES_DB}  # Use the environment variable from .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 3s
