services:
  frontend:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./react-vite/dist:/usr/share/nginx/html  
    depends_on:
      - api

  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_DEBUG: 0 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 3s