from app.models import db, Article, environment, SCHEMA
from datetime import datetime, timedelta
import json
from sqlalchemy.sql import text  

def seed_articles():
    articles = [
        {
            "title": "The Future of Renewable Energy",
            "display_type": "headline",
            "content": "Exploring the advancements in solar and wind energy technologies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "renewable_energy.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/solar_energy",
            "location": "Global",
            "contributors": "John Doe, Jane Smith",
            "author_id": 1,
            "section": "technology",
            "tags": json.dumps(["renewable", "energy", "solar", "wind"]),
            "created_at": datetime.utcnow() - timedelta(days=10),
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])

        },
        {
            "title": "Top 10 Tech Gadgets of 2023",
            "display_type": "list",
            "content": "A curated list of the most innovative gadgets this year.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "tech_gadgets.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/tech_gadgets",
            "location": "USA",
            "contributors": "Alice Johnson",
            "author_id": 2,
            "section": "technology",
            "tags": json.dumps(["gadgets", "tech", "2023"]),
            "created_at": datetime.utcnow() - timedelta(days=9),             
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "Global Markets React to New Policies",
            "display_type": "sidebar_1",
            "content": "How recent policy changes are affecting global markets. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "global_markets.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/global_markets",
            "location": "World",
            "contributors": "Bob Brown",
            "author_id": 3,
            "section": "business",
            "tags": json.dumps(["markets", "policies", "global"]),
            "created_at": datetime.utcnow() - timedelta(days=8), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Rise of E-Sports",
            "display_type": "headline",
            "content": "E-Sports is becoming a major player in the sports industry.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "esports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/esports",
            "location": "Global",
            "contributors": "Charlie Davis",
            "author_id": 4,
            "section": "sports",
            "tags": json.dumps(["esports", "gaming", "sports"]),
            "created_at": datetime.utcnow() - timedelta(days=7), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "Hollywood's Newest Blockbusters",
            "display_type": "sidebar_2",
            "content": "A look at the most anticipated movies of the year. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "hollywood.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/hollywood",
            "location": "USA",
            "contributors": "Diana Evans",
            "author_id": 1,
            "section": "entertainment",
            "tags": json.dumps(["hollywood", "movies", "blockbusters"]),
            "created_at": datetime.utcnow() - timedelta(days=6), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Impact of AI on Healthcare",
            "display_type": "ads_2",
            "content": "How AI is revolutionizing the healthcare industry. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "ai_healthcare.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/ai_healthcare",
            "location": "Global",
            "contributors": "Ethan Harris",
            "author_id": 2,
            "section": "technology",
            "tags": json.dumps(["AI", "healthcare", "technology"]),
            "created_at": datetime.utcnow() - timedelta(days=5), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Best Travel Destinations for 2023",
            "display_type": "list",
            "content": "Top destinations to visit this year. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "travel.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/travel",
            "location": "Global",
            "contributors": "Fiona Green",
            "author_id": 3,
            "section": "world",
            "tags": json.dumps(["travel", "destinations", "2023"]),
            "created_at": datetime.utcnow() - timedelta(days=4), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Evolution of Smartphones",
            "display_type": "sidebar_3",
            "content": "A look at how smartphones have evolved over the years. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "smartphones.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/smartphones",
            "location": "Global",
            "contributors": "George White",
            "author_id": 4,
            "section": "technology",
            "tags": json.dumps(["smartphones", "tech", "evolution"]),
            "created_at": datetime.utcnow() - timedelta(days=3), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Work: Remote vs Office",
            "display_type": "headline",
            "content": "Debating the future of work environments. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "future_work.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/future_work",
            "location": "Global",
            "contributors": "Hannah Black",
            "author_id": 1,
            "section": "business",
            "tags": json.dumps(["work", "remote", "office"]),
            "created_at": datetime.utcnow() - timedelta(days=2), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Rise of Plant-Based Diets",
            "display_type": "ads_2",
            "content": "How plant-based diets are becoming more popular. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "plant_based.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/plant_based",
            "location": "Global",
            "contributors": "Ian Blue",
            "author_id": 2,
            "section": "national",
            "tags": json.dumps(["diet", "plant-based", "health"]),
            "created_at": datetime.utcnow() - timedelta(days=1), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Impact of Climate Change on Agriculture",
            "display_type": "headline",
            "content": "How climate change is affecting farming practices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "climate_agriculture.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/climate_agriculture",
            "location": "Global",
            "contributors": "Jack Red",
            "author_id": 3,
            "section": "national",
            "tags": json.dumps(["climate", "agriculture", "farming"]),
            "created_at": datetime.utcnow() - timedelta(days=15), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Space Exploration",
            "display_type": "headline",
            "content": "What's next for humanity in space? Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "space_exploration.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/space_exploration",
            "location": "Global",
            "contributors": "Karen Yellow",
            "author_id": 4,
            "section": "technology",
            "tags": json.dumps(["space", "exploration", "future"]),
            "created_at": datetime.utcnow() - timedelta(days=14), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Role of Big Data in Business",
            "display_type": "sidebar_1",
            "content": "How big data is transforming business strategies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "big_data.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/big_data",
            "location": "Global",
            "contributors": "Leo Green",
            "author_id": 1,
            "section": "business",
            "tags": json.dumps(["big data", "business", "analytics"]),
            "created_at": datetime.utcnow() - timedelta(days=13), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Rise of Virtual Reality",
            "display_type": "headline",
            "content": "How VR is changing the way we experience the world. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "virtual_reality.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/virtual_reality",
            "location": "Global",
            "contributors": "Mia Orange",
            "author_id": 2,
            "section": "technology",
            "tags": json.dumps(["VR", "virtual reality", "tech"]),
            "created_at": datetime.utcnow() - timedelta(days=12), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Electric Vehicles",
            "display_type": "headline",
            "content": "What's next for the EV industry? Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "electric_vehicles.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/electric_vehicles",
            "location": "Global",
            "contributors": "Noah Purple",
            "author_id": 3,
            "section": "technology",
            "tags": json.dumps(["EV", "electric vehicles", "future"]),
            "created_at": datetime.utcnow() - timedelta(days=11), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Impact of Social Media on Mental Health",
            "display_type": "headline",
            "content": "How social media is affecting our mental well-being. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "social_media.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/social_media",
            "location": "Global",
            "contributors": "Olivia Pink",
            "author_id": 4,
            "section": "national",
            "tags": json.dumps(["social media", "mental health", "well-being"]),
            "created_at": datetime.utcnow() - timedelta(days=10), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Quantum Computing",
            "display_type": "headline",
            "content": "How quantum computing could revolutionize technology. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "quantum_computing.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/quantum_computing",
            "location": "Global",
            "contributors": "Peter Brown",
            "author_id": 1,
            "section": "technology",
            "tags": json.dumps(["quantum", "computing", "future"]),
            "created_at": datetime.utcnow() - timedelta(days=9), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Rise of Online Education",
            "display_type": "headline",
            "content": "How online learning is transforming education. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "online_education.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/online_education",
            "location": "Global",
            "contributors": "Quinn Gray",
            "author_id": 2,
            "section": "national",
            "tags": json.dumps(["education", "online", "learning"]),
            "created_at": datetime.utcnow() - timedelta(days=8), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Impact of 5G on Mobile Technology",
            "display_type": "headline",
            "content": "How 5G is changing the mobile landscape. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "5g_technology.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/5g_technology",
            "location": "Global",
            "contributors": "Rachel White",
            "author_id": 3,
            "section": "technology",
            "tags": json.dumps(["5G", "mobile", "technology"]),
            "created_at": datetime.utcnow() - timedelta(days=7), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Cybersecurity",
            "display_type": "headline",
            "content": "What's next in the fight against cyber threats? Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "cybersecurity.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/cybersecurity",
            "location": "Global",
            "contributors": "Sam Black",
            "author_id": 4,
            "section": "technology",
            "tags": json.dumps(["cybersecurity", "future", "tech"]),
            "created_at": datetime.utcnow() - timedelta(days=6), 
            "version_history": json.dumps([{"version": 1, "updated_at": (datetime.utcnow() - timedelta(days=10)).isoformat(), "changes": "Initial version"}])
        },
        {
            "title": "The Future of Artificial Intelligence",
            "display_type": "headline",
            "content": "Exploring how AI is revolutionizing industries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_technology.WebP ",
            "youtube_embed_url": "https://www.youtube.com/embed/artificial_intelligence",
            "location": "Global",
            "contributors": "John Smith",
            "author_id": 2,
            "section": "technology",
            "tags": "[\"AI\", \"artificial intelligence\", \"tech\"]",
            "created_at": "2023-10-01T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-10-02T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Blockchain: Beyond Cryptocurrency",
            "display_type": "headline",
            "content": "Understanding the broader applications of blockchain technology. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_technology.WebP ",
            "youtube_embed_url": "https://www.youtube.com/embed/blockchain_tech",
            "location": "Global",
            "contributors": "Emma Watson",
            "author_id": 3,
            "section": "technology",
            "tags": "[\"blockchain\", \"cryptocurrency\", \"tech\"]",
            "created_at": "2023-09-25T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-26T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Evolution of Quantum Computing",
            "display_type": "ads_1",
            "content": "How quantum computing is set to transform the tech landscape. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_technology.WebP ",
            "youtube_embed_url": "https://www.youtube.com/embed/quantum_computing",
            "location": "Global",
            "contributors": "Alex Johnson",
            "author_id": 1,
            "section": "technology",
            "tags": "[\"quantum computing\", \"tech\", \"future tech\"]",
            "created_at": "2023-09-20T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-21T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "5G: The Next Generation of Connectivity",
            "display_type": "headline",
            "content": "The impact of 5G on communication and technology. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_technology.WebP ",
            "youtube_embed_url": "https://www.youtube.com/embed/5g_technology",
            "location": "Global",
            "contributors": "Sarah Lee",
            "author_id": 4,
            "section": "technology",
            "tags": "[\"5G\", \"connectivity\", \"tech\"]",
            "created_at": "2023-09-15T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-16T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Role of IoT in Smart Cities",
            "display_type": "headline",
            "content": "How the Internet of Things is shaping the future of urban living. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_technology.WebP ",
            "youtube_embed_url": "https://www.youtube.com/embed/iot_smart_cities",
            "location": "Global",
            "contributors": "Michael Brown",
            "author_id": 2,
            "section": "technology",
            "tags": "[\"IoT\", \"smart cities\", \"tech\"]",
            "created_at": "2023-09-10T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-11T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Future of Urban Transportation",
            "display_type": "headline",
            "content": "Exploring how cities are evolving with new transportation technologies. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/urban_transport",
            "location": "Global",
            "contributors": "John Doe",
            "author_id": 1,
            "section": "national",
            "tags": "[\"transportation\", \"urban\", \"tech\"]",
            "created_at": "2023-09-20T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-22T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Advancements in Renewable Energy",
            "display_type": "headline",
            "content": "How renewable energy sources are shaping the future of power. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/renewable_energy",
            "location": "Global",
            "contributors": "Jane Smith",
            "author_id": 2,
            "section": "national",
            "tags": "[\"energy\", \"renewable\", \"environment\"]",
            "created_at": "2023-09-18T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-20T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Impact of AI on Healthcare",
            "display_type": "headline",
            "content": "Examining the role of artificial intelligence in modern healthcare. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/ai_healthcare",
            "location": "Global",
            "contributors": "Alice Johnson",
            "author_id": 3,
            "section": "national",
            "tags": "[\"AI\", \"healthcare\", \"tech\"]",
            "created_at": "2023-09-15T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-17T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Evolution of E-Learning",
            "display_type": "headline",
            "content": "How online education is transforming traditional learning. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/e_learning",
            "location": "Global",
            "contributors": "Bob Brown",
            "author_id": 4,
            "section": "national",
            "tags": "[\"education\", \"e-learning\", \"tech\"]",
            "created_at": "2023-09-12T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-14T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Smart Cities",
            "display_type": "ads_1",
            "content": "How technology is making cities smarter and more efficient. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/smart_cities",
            "location": "Global",
            "contributors": "Charlie Davis",
            "author_id": 1,
            "section": "national",
            "tags": "[\"smart cities\", \"urban\", \"tech\"]",
            "created_at": "2023-09-10T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-12T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Future of Work: Remote and Hybrid Models",
            "display_type": "headline",
            "content": "How remote and hybrid work models are reshaping the workplace. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/future_of_work",
            "location": "Global",
            "contributors": "Eva Green",
            "author_id": 2,
            "section": "national",
            "tags": "[\"work\", \"remote\", \"hybrid\"]",
            "created_at": "2023-09-08T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-10T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Role of Big Data in Modern Business",
            "display_type": "headline",
            "content": "How big data is driving decision-making in businesses today. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/big_data",
            "location": "Global",
            "contributors": "Frank White",
            "author_id": 3,
            "section": "national",
            "tags": "[\"big data\", \"business\", \"tech\"]",
            "created_at": "2023-09-05T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-07T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Growth of the Gig Economy",
            "display_type": "headline",
            "content": "Exploring the rise and impact of the gig economy. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/gig_economy",
            "location": "Global",
            "contributors": "Grace Lee",
            "author_id": 4,
            "section": "national",
            "tags": "[\"gig economy\", \"work\", \"economy\"]",
            "created_at": "2023-09-02T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-04T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Impact of Climate Change on Agriculture",
            "display_type": "headline",
            "content": "How climate change is affecting farming and food production. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/climate_agriculture",
            "location": "Global",
            "contributors": "Henry Black",
            "author_id": 1,
            "section": "national",
            "tags": "[\"climate change\", \"agriculture\", \"environment\"]",
            "created_at": "2023-08-30T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-01T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Cybersecurity Threats",
            "display_type": "headline",
            "content": "How increasing cybersecurity threats are shaping the digital landscape. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "image_filename": "default_national.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/cybersecurity",
            "location": "Global",
            "contributors": "Ivy Blue",
            "author_id": 2,
            "section": "national",
            "tags": "[\"cybersecurity\", \"tech\", \"security\"]",
            "created_at": "2023-08-28T08:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-08-30T08:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Climate Change Summit",
            "display_type": "headline",
            "content": "World leaders gather to discuss urgent climate action. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/climate_summit",
            "location": "Global",
            "contributors": "John Green",
            "author_id": 1,
            "section": "world",
            "tags": "[\"climate\", \"environment\", \"global\"]",
            "created_at": "2023-10-01T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-10-02T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "International Space Station Milestone",
            "display_type": "headline",
            "content": "The ISS celebrates 25 years of human presence in space. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/iss_milestone",
            "location": "Global",
            "contributors": "Sarah Blue",
            "author_id": 2,
            "section": "world",
            "tags": "[\"space\", \"ISS\", \"science\"]",
            "created_at": "2023-09-28T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-29T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Economic Forum",
            "display_type": "headline",
            "content": "Experts discuss the future of the global economy. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/economic_forum",
            "location": "Global",
            "contributors": "Emma Red",
            "author_id": 3,
            "section": "world",
            "tags": "[\"economy\", \"global\", \"finance\"]",
            "created_at": "2023-09-25T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-26T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "World Health Organization Report",
            "display_type": "headline",
            "content": "New findings on global health trends. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/health_report",
            "location": "Global",
            "contributors": "Liam Yellow",
            "author_id": 4,
            "section": "world",
            "tags": "[\"health\", \"WHO\", \"global\"]",
            "created_at": "2023-09-22T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-23T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Education Initiative",
            "display_type": "headline",
            "content": "New programs aim to improve education worldwide. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/education_initiative",
            "location": "Global",
            "contributors": "Olivia Purple",
            "author_id": 1,
            "section": "world",
            "tags": "[\"education\", \"global\", \"initiative\"]",
            "created_at": "2023-09-19T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-20T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Tech Innovation",
            "display_type": "headline",
            "content": "How technology is shaping the future globally. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/tech_innovation",
            "location": "Global",
            "contributors": "Noah Black",
            "author_id": 2,
            "section": "world",
            "tags": "[\"tech\", \"innovation\", \"global\"]",
            "created_at": "2023-09-16T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-17T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Art Exhibition",
            "display_type": "headline",
            "content": "Artists from around the world showcase their work. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/art_exhibition",
            "location": "Global",
            "contributors": "Ava White",
            "author_id": 3,
            "section": "world",
            "tags": "[\"art\", \"global\", \"exhibition\"]",
            "created_at": "2023-09-13T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-14T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Music Festival",
            "display_type": "headline",
            "content": "A celebration of music from different cultures. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/music_festival",
            "location": "Global",
            "contributors": "William Brown",
            "author_id": 4,
            "section": "world",
            "tags": "[\"music\", \"festival\", \"global\"]",
            "created_at": "2023-09-10T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-11T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Food Security",
            "display_type": "headline",
            "content": "Efforts to ensure food security worldwide. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/food_security",
            "location": "Global",
            "contributors": "Sophia Green",
            "author_id": 1,
            "section": "world",
            "tags": "[\"food\", \"security\", \"global\"]",
            "created_at": "2023-09-07T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-08T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Water Crisis",
            "display_type": "headline",
            "content": "Addressing the global water scarcity issue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/water_crisis",
            "location": "Global",
            "contributors": "James Blue",
            "author_id": 2,
            "section": "world",
            "tags": "[\"water\", \"crisis\", \"global\"]",
            "created_at": "2023-09-04T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-05T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Wildlife Conservation",
            "display_type": "headline",
            "content": "Efforts to protect endangered species worldwide. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/wildlife_conservation",
            "location": "Global",
            "contributors": "Isabella Red",
            "author_id": 3,
            "section": "world",
            "tags": "[\"wildlife\", \"conservation\", \"global\"]",
            "created_at": "2023-09-01T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-02T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Renewable Energy",
            "display_type": "headline",
            "content": "Advancements in renewable energy sources. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_world.png",
            "youtube_embed_url": "https://www.youtube.com/embed/renewable_energy",
            "location": "Global",
            "contributors": "Lucas Yellow",
            "author_id": 4,
            "section": "world",
            "tags": "[\"energy\", \"renewable\", \"global\"]",
            "created_at": "2023-08-29T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-08-30T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },{
            "title": "The Future of Remote Work",
            "display_type": "headline",
            "content": "How remote work is reshaping the corporate landscape. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_business.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/remote_work",
            "location": "Global",
            "contributors": "John Smith",
            "author_id": 3,
            "section": "business",
            "tags": "[\"remote work\", \"business\", \"corporate\"]",
            "created_at": "2023-10-01T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-10-01T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Cryptocurrency Trends in 2023",
            "display_type": "headline",
            "content": "Exploring the latest trends in cryptocurrency and blockchain technology. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_business.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/crypto_trends",
            "location": "Global",
            "contributors": "Emma Green",
            "author_id": 1,
            "section": "business",
            "tags": "[\"cryptocurrency\", \"blockchain\", \"finance\"]",
            "created_at": "2023-09-25T09:30:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-25T09:30:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Green Energy Investments",
            "display_type": "headline",
            "content": "How green energy is becoming a major focus for investors. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_business.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/green_energy",
            "location": "Global",
            "contributors": "Liam Brown",
            "author_id": 4,
            "section": "business",
            "tags": "[\"green energy\", \"investments\", \"sustainability\"]",
            "created_at": "2023-09-20T15:45:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-20T15:45:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Impact of AI on Business Operations",
            "display_type": "headline",
            "content": "How artificial intelligence is transforming business processes. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_business.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/ai_business",
            "location": "Global",
            "contributors": "Sophia White",
            "author_id": 2,
            "section": "business",
            "tags": "[\"AI\", \"business\", \"automation\"]",
            "created_at": "2023-09-15T11:20:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-15T11:20:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "Global Supply Chain Challenges in 2023",
            "display_type": "headline",
            "content": "Examining the ongoing challenges in global supply chains. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_business.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/supply_chain",
            "location": "Global",
            "contributors": "Noah Taylor",
            "author_id": 3,
            "section": "business",
            "tags": "[\"supply chain\", \"logistics\", \"business\"]",
            "created_at": "2023-09-10T14:10:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-10T14:10:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Evolution of Esports",
            "display_type": "headline",
            "content": "How esports is becoming a mainstream phenomenon. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_sports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/esports_evolution",
            "location": "Global",
            "contributors": "Oliver Black",
            "author_id": 2,
            "section": "sports",
            "tags": "[\"esports\", \"gaming\", \"sports\"]",
            "created_at": "2023-10-05T10:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-10-05T10:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Women's Football",
            "display_type": "headline",
            "content": "How women's football is gaining global recognition. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_sports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/womens_football",
            "location": "Global",
            "contributors": "Ava Blue",
            "author_id": 1,
            "section": "sports",
            "tags": "[\"football\", \"womens sports\", \"sports\"]",
            "created_at": "2023-09-28T08:15:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-28T08:15:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Impact of Technology on Sports Training",
            "display_type": "headline",
            "content": "How technology is revolutionizing sports training and performance. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_sports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/sports_tech",
            "location": "Global",
            "contributors": "William Green",
            "author_id": 4,
            "section": "sports",
            "tags": "[\"sports tech\", \"training\", \"performance\"]",
            "created_at": "2023-09-22T13:30:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-22T13:30:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Future of Olympic Games",
            "display_type": "headline",
            "content": "Exploring the future of the Olympic Games in a changing world. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_sports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/olympic_future",
            "location": "Global",
            "contributors": "Isabella Yellow",
            "author_id": 3,
            "section": "sports",
            "tags": "[\"olympics\", \"sports\", \"future\"]",
            "created_at": "2023-09-18T16:45:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-18T16:45:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Growing Popularity of Extreme Sports",
            "display_type": "headline",
            "content": "How extreme sports are capturing the attention of thrill-seekers. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_sports.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/extreme_sports",
            "location": "Global",
            "contributors": "James Red",
            "author_id": 2,
            "section": "sports",
            "tags": "[\"extreme sports\", \"adventure\", \"sports\"]",
            "created_at": "2023-09-12T12:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-12T12:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Streaming Platforms",
            "display_type": "headline",
            "content": "How streaming platforms are changing the entertainment industry. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_entertainment.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/streaming_rise",
            "location": "Global",
            "contributors": "Emily Purple",
            "author_id": 1,
            "section": "entertainment",
            "tags": "[\"streaming\", \"entertainment\", \"media\"]",
            "created_at": "2023-10-03T14:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-10-03T14:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Evolution of Music Festivals",
            "display_type": "headline",
            "content": "How music festivals are adapting to new trends and technologies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_entertainment.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/music_festivals",
            "location": "Global",
            "contributors": "Daniel Pink",
            "author_id": 4,
            "section": "entertainment",
            "tags": "[\"music festivals\", \"entertainment\", \"music\"]",
            "created_at": "2023-09-26T11:30:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-26T11:30:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Impact of Social Media on Celebrity Culture",
            "display_type": "headline",
            "content": "How social media is reshaping celebrity culture and fan engagement. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_entertainment.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/social_media_celebrities",
            "location": "Global",
            "contributors": "Charlotte Gray",
            "author_id": 2,
            "section": "entertainment",
            "tags": "[\"social media\", \"celebrities\", \"entertainment\"]",
            "created_at": "2023-09-21T17:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-21T17:00:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Future of Movie Theaters",
            "display_type": "headline",
            "content": "How movie theaters are adapting to the rise of streaming. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_entertainment.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/movie_theaters",
            "location": "Global",
            "contributors": "Ethan Orange",
            "author_id": 3,
            "section": "entertainment",
            "tags": "[\"movie theaters\", \"entertainment\", \"streaming\"]",
            "created_at": "2023-09-16T10:45:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-16T10:45:00Z\", \"changes\": \"Initial version\"}]"
        },
        {
            "title": "The Rise of Virtual Concerts",
            "display_type": "headline",
            "content": "How virtual concerts are becoming a new norm in the music industry. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "image_filename": "default_entertainment.jpg",
            "youtube_embed_url": "https://www.youtube.com/embed/virtual_concerts",
            "location": "Global",
            "contributors": "Mia Brown",
            "author_id": 1,
            "section": "entertainment",
            "tags": "[\"virtual concerts\", \"music\", \"entertainment\"]",
            "created_at": "2023-09-11T09:00:00Z",
            "version_history": "[{\"version\": 1, \"updated_at\": \"2023-09-11T09:00:00Z\", \"changes\": \"Initial version\"}]"
        }
    ]

    for article_data in articles:
        # Create an Article instance
        article = Article(
            title=article_data["title"],
            display_type=article_data["display_type"],
            content=article_data["content"],
            image_filename=article_data["image_filename"],
            youtube_embed_url=article_data["youtube_embed_url"],
            location=article_data["location"],
            contributors=article_data["contributors"],
            author_id=article_data["author_id"],
            section=article_data["section"],
            tags=article_data["tags"],
            version_history=article_data["version_history"],
            created_at=article_data["created_at"]
        )
        db.session.add(article)

    db.session.commit()  # Commit once after all articles are added
    print("Articles have been seeded!")

def undo_articles():
    try:
        if environment == "production":
            # Use text() to wrap the raw SQL query
            db.session.execute(text(f"TRUNCATE TABLE {SCHEMA}.articles RESTART IDENTITY CASCADE;"))
        else:
            # Use text() to wrap the raw SQL query
            db.session.execute(text("DELETE FROM articles"))

        db.session.commit()
        print("Articles have been removed!")
    except Exception as e:
        db.session.rollback()  # Rolls back the transaction on failure
        print(f"Error undoing articles seed: {e}")